components:
  terraform:
    app:
      metadata:
        component: ecs-task
      vars:
        name: app
        ecs: !terraform.state ecs/cluster .
        vpc: !terraform.state vpc .
        lb: !terraform.state ecs/cluster .alb.public
        base_domains: !terraform.state ecs/cluster .records
        containers:
          app:
            image: !env APP_IMAGE 068007702576.dkr.ecr.us-east-2.amazonaws.com/cloudposse-examples/app-on-ecs-v2:sha-2ee4206
            memory: 256
            portMappings:
              - containerPort: 8080
            environment:
              - name: COLOR
                value: blue
            healthCheck:
              command: ["CMD-SHELL", "curl -f http://localhost:8080/healthz || exit 1"]
              interval: 5
              retries: 3
              startPeriod: 5
              timeout: 3
            logConfiguration:
                logDriver: "awslogs"
                options:
                    awslogs-create-group: true
                    awslogs-group: "app"
                    awslogs-region: "us-east-2"
                    awslogs-stream-prefix: "app"
        url_path: /dashboard
        autoscaling:
          min_capacity: 2
          max_capacity: 4
          scale_up_cooldown: 30
          scale_down_cooldown: 60
          rule:
            high:
              threshold: 30
              period: 60
            low:
              threshold: 10
              period: 60

