name: Main Branch
on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  release:
    runs-on: ["ubuntu-latest"]
    steps:
      - name: Create/Update Draft release
        uses: release-drafter/release-drafter@v7
        with:
          publish: false
          prerelease: false
          config-name: configs/draft-release.yml
          commitish: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
