name: Main Branch
on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: write
  statuses: write

env:
  ATMOS_PROFILE: github

jobs:
  test:
    needs: [ build ]
    runs-on: ["ubuntu-latest"]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: app/go.mod
          cache-dependency-path: app/go.mod

      - name: Run tests
        working-directory: app
        run: go test -v ./...

  build:
    runs-on: ["ubuntu-latest"]
    steps:
      - name: Install Atmos
        uses: cloudposse/github-action-setup-atmos@v3
        with:
          install-wrapper: false
          atmos-version: ${{ vars.ATMOS_VERSION }}

      - name: Checkout
        uses: actions/checkout@v6

      - name: AWS Auth
        shell: bash
        run: |
          atmos auth env --identity plat-dev/terraform --format dotenv | tr -d "'" >> $GITHUB_ENV
          atmos auth login --identity plat-dev/terraform

      - name: Build
        id: build
        uses: cloudposse/github-action-docker-build-push@v3
        with:
          organization: cloudposse-examples
          repository: app-on-ecs-v2
          registry: ${{ vars.ECR_REGISTRY }}
          workdir: app

    outputs:
      image: ${{ steps.build.outputs.image }}
      tag: ${{ steps.build.outputs.tag }}
      
  deploy:
    needs: [ test, build ]
    runs-on: ["ubuntu-latest"]
    environment:
      name: dev
      url: ${{ steps.deploy.outputs.output_url }}
    steps:
      - name: Install Atmos
        uses: cloudposse/github-action-setup-atmos@v3
        with:
          install-wrapper: false
          atmos-version: ${{ vars.ATMOS_VERSION }}

      - name: Checkout
        uses: actions/checkout@v6

      - name: Deploy ECS Service
        shell: bash
        id: deploy
        env:
          APP_IMAGE: "${{ needs.build.outputs.image }}:${{ needs.build.outputs.tag }}"
        run: |
          atmos terraform deploy app -s dev

  release:
    runs-on: ["ubuntu-latest"]
    needs: [ deploy ]
    steps:
      - name: Create/Update Draft release
        uses: release-drafter/release-drafter@v7
        with:
          publish: false
          prerelease: false
          config-name: configs/draft-release.yml
          commitish: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
